export const USER_LOGGED = 'USER_LOGGED'
export const USER_LOGGED_ACTION = 'USER_LOGGED_ACTION'
export const USER_LOGGED_LOADING = 'USER_LOGGED_LOADING'
export const USER_LOGGED_FAILED = 'USER_LOGGED_FAILED'

export const USER_LOGOUT = 'USER_LOGOUT'
export const USER_LOGOUT_ACTION = 'USER_LOGOUT_ACTION'
export const USER_LOGOUT_LOADING = 'USER_LOGOUT_LOADING'

export const USER_SIGNED = 'USER_SIGNED'
export const USER_SIGNED_ACTION = 'USER_SIGNED_ACTION'
export const USER_SIGNED_LOADING = 'USER_SIGNED_LOADING'
