export const USER_LOGGED = 'USER_LOGGED'
export const USER_LOGGED_ACTION = 'USER_LOGGED_ACTION'
export const USER_LOGGED_LOADING = 'USER_LOGGED_LOADING'
export const USER_LOGGED_FAILED = 'USER_LOGGED_FAILED'

export const USER_LOGOUT = 'USER_LOGOUT'
export const USER_LOGOUT_ACTION = 'USER_LOGOUT_ACTION'
export const USER_LOGOUT_LOADING = 'USER_LOGOUT_LOADING'

export const USER_SIGNED = 'USER_SIGNED'
export const USER_SIGNED_ACTION = 'USER_SIGNED_ACTION'
export const USER_SIGNED_LOADING = 'USER_SIGNED_LOADING'

export const PRINTER_ADD = 'PRINTER_ADD'
export const PRINTER_ADD_ACTION = 'PRINTER_ADD_ACTION'
export const PRINTER_ADD_LOADING = 'PRINTER_ADD_LOADING'

export const PRINTER_REMOVE = 'PRINTER_REMOVE'
export const PRINTER_REMOVE_ACTION = 'PRINTER_REMOVE_ACTION'
export const PRINTER_REMOVE_LOADING = 'PRINTER_REMOVE_LOADING'

export const PRINTER_UPDATE = 'PRINTER_UPDATE'
export const PRINTER_SAVE = 'PRINTER_SAVE'
export const PRINTER_SAVE_ACTION = 'PRINTER_SAVE_ACTION'
export const PRINTER_UPDATE_ACTION = 'PRINTER_UPDATE_ACTION'
export const PRINTER_UPDATE_LOADING = 'PRINTER_UPDATE_LOADING'

export const PRINTER_WIZARD = 'PRINTER_WIZARD'
export const PRINTER_WIZARD_ACTION = 'PRINTER_WIZARD_ACTION'

export const LIST_REPORTS_ACTION = 'LIST_REPORTS_ACTION';
export const LIST_REPORTS_ACTION_COMPLETE = 'LIST_REPORTS_ACTION_COMPLETE';
export const LIST_REPORTS_ACTION_FAIL = 'LIST_REPORTS_ACTION_FAIL';

export const GET_REPORT_DATA_ACTION = 'GET_REPORT_DATA_ACTION';
export const GET_REPORT_DATA_ACTION_COMPLETE = 'GET_REPORT_DATA_ACTION_COMPLETE';
export const GET_REPORT_DATA_ACTION_FAIL = 'GET_REPORT_DATA_ACTION_FAIL';

export const getSessionId = (state) => state.user.sessionId

export const DIMENSIONS_CHANGE_ACTION = 'DIMENSIONS_CHANGE_ACTION';
