# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'PaygatePOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PaygatePOS
  pod 'AppCenter/Crashes', '~> 1.7.1'
  pod 'AppCenter/Analytics', '~> 1.7.1'
  pod 'AppCenterReactNativeShared', '~> 1.6.0'

  pod 'RNFS', :path => '../node_modules/react-native-fs'

  pod 'RNSVG', :path => '../node_modules/react-native-svg'

end

target 'PaygatePOS-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PaygatePOS-tvOS

  target 'PaygatePOS-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
